### ISSUE TITLE
The theme `*.scss` files are all ignored

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-indigo#24]
All scss files that ship with this theme (including "_extras.scss") are not rendered in the Tutor project environment. That's because they are located in a "partials" folder which is explicitly ignored by Tutor: https://github.com/overhangio/tutor/blob/669f8363283c5351ff39007e06df42dd1c48b2c7/tutor/env.py#L75

This issue was detected in this conversation: https://github.com/overhangio/tutor-indigo/pull/23#issuecomment-1141198222

The proper solution would probably be to move the files from the "partials" folder and put them directly in the "indigo" directory. I need to check whether this would be working.

**Comment by insad** [comment]
I suppose in my installation this is still working correctly, because I'm not using the tutor-indigo plugin version, but still the old version (using `tutor config render`).
Have also some more suggestions for the indigo theme, like using a secondary color, and making the height of the logo adjustable, but will leave these until you can sort this problem out.
