### ISSUE TITLE
Apps MFE does not inherit INDIGO_* settings

### ISSUE THREAD

**Issue by misilot** [overhangio/tutor-indigo#66]
The apps MFE does not inherit the INDIGO_ settings such as 

```
INDIGO_FOOTER_LEGAL_LINKS
INDIGO_FOOTER_NAV_LINKS
INDIGO_PRIMARY_COLOR
```

**Comment by DawoudSheraz** [comment]
@misilot Hello. The current description does not have enough context for the underlying issue. Can you add more details about the issue, its impact, etc.? Thanks

**Comment by hinakhadim** [comment]
Hi @misilot , Currently the MFEs don't get the INDIGO_ settings. The Links settings don't passed to MFEs because these are the array and the primary color settings don't passed to MFEs because MFEs are styled using `brand-openedx` npm package. Therefore, It doesn't make sense to pass theme_color variable to MFEs when it is of no use. Furthermore, the community has added [ADR](https://github.com/openedx/frontend-component-footer/pull/326) for making footer-links consistent on overall platform (including LMS and MFEs). But development on it is paused now, as we are exploring UI Plugin Approach for MFEs. This is where community is looking at. If there's anything I missed, feel free to share.
