### ISSUE TITLE
Learning MFE header text is smushed onto one line

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/tutor-indigo#76]
## Screenshots

Seems like the header text either needs to be broken into two lines, or it needs some padding tweaks that it looks better on one line.

### Without tutor-indigo installed:

![image](https://github.com/overhangio/tutor-indigo/assets/3628148/3928a57c-9029-48d4-9087-ef835eb85c43)

### With tutor-indigo installed

![image](https://github.com/overhangio/tutor-indigo/assets/3628148/cccc51d7-2ef7-4649-9465-7563b21f281d)

## Reproduction

Simply install indigo, enable it, rebuild the MFE image, start Tutor, and navigate to a course.

This does not seem to be impacting Quince. I believe it only impacts Nightly. I tested both `tutor local` and `tutor dev`. I did not try mounting frontend-app-learning.

System info:

```
(venv-tutor) ~/overhangio/tutor 🍀 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

(venv-tutor) ~/overhangio/tutor 🍀 tutor plugins list -e
NAME  	STATUS   	VERSION
indigo	✅ enabled	17.3.0
mfe   	✅ enabled	17.0.0
```

Both indigo and mfe are installed from a local git-clone at the tip of their `nightly` branches.

**Comment by hinakhadim** [comment]
Thanks for creating the issue. It has been resolved in `@edly-io/indigo-brand-openedx@1.4.1` as the styling of MFEs and its components depend on this package.

Why it has not been resolved in `tutor-indigo`?
Due to incompatibility issues in MFEs (master branch) and header component versions, we have decided to remove Indigo header component and would use the bydefault openedx header component. Since the brand package styles are applied on classes which are identical in both indigo header and openedx header, that's disturbed the styling of openedx header when removing the indigo header. 
Workaround: Add a custom class to indigo header and did styling in brand on the basis of that class for header component. So, The styling of indigo header won't affect the openedx header styles now.
